version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: npm ci

      # {{ the build would normally happen here }}

      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm

  snyk_scan:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: Snyk Setup
          command: |
            curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
            chmod +x ./snyk
            ./snyk auth $SNYK_TOKEN

      - run:
          name: Snyk Test
          command: |
            ./snyk test --fail-on=upgradable --severity-threshold=high --org=$SNYK_ORG


# Invoke jobs via workflows
workflows:
  default:
    jobs:
      - build
      - snyk_scan:
          requires:
            - build
